# Alacritty configuration
general.import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = false

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12
